version: '3'
services:
  bsk-remote-factorisation:
    build: .
    command: nsjail -Ml --port 37635 --user 99999 --group 99999  --disable_proc --chroot /task --time_limit 18 -R /lib/ -R /lib64/ -R /usr/lib/ -R /bin/ -R /usr/bin/factor actual/remote_factor
    ports:
      - "40021:37635"
    restart: always
    privileged: true
