version: '3'
services:
  bsk-leetime:
    build: .
    command: bash -c "rm -rf tmp; bundle exec rails server -p 3000 -b '0.0.0.0' --environment production"
    ports:
      - "40002:3000"
    restart: always
    environment:
      - SECRET_KEY_BASE=aASD()A&(*@!#YDSAJKCZX__xzcZC_CKZLXCJxklCJ@#*JEQDaS
